networks:
  videocutter_network:
    driver: bridge

services:
  videocutter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videocutter
    ports:
      - "${PORT:-8080}:8080"
    networks:
      - videocutter_network
    environment:
      - PORT=8080
      - LOG_REQUESTS=${LOG_REQUESTS:-false}
      - LOG_LEVEL=${LOG_LEVEL:-error}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
